### PR TITLE
[Fix] Fix import error in `optimize_anchors.py` 

### PR DESCRIPTION
**Pull request by VoyagerXvoyagerx**
## Motivation

the `build_dataset` module is removed in mmdet 3.0.0rc5

## Modification

from mmyolo.registry import DATASETS
build dataset from class `DATASETS`

### CODE REVIEW

**Review by hhaAndroid — APPROVED** [review]

**Comment by ODAncona** [comment]
Oh okay,

I think the demo file `MMDet_InstanceSeg_Tutorial.ipynb` could be updated then. I'm unable to use it with 3.1

**Comment by muneebelahimalik** [comment]
> from mmyolo.registry import DATASETS

Hey!
Were you able to run it with 3.1 mmdet version?

**Comment by haoweiz23** [comment]
So there is no 'build_dataset ' function any more? Any replace function?

**Comment by zoldaten** [comment]
@haoweiz23 its in runner.train()  now as i suppose.

i fixed a bit MMSegmentation_Tutorial.ipynb and it works in inference
but it still has an issue with train (
[MMSegmentation_Tutorial_my.ipynb](https://github.com/user-attachments/files/23910534/MMSegmentation_Tutorial_my.ipynb)

**Pull request merged**
