### PR TITLE
[Feature] Support PyTorch model forward for TensorRT inference

### PR DESCRIPTION
**Pull request by triple-Mu**
Support pytorch model forward for TensorRT inference.
Pytorch forward will be faster than normal python object `__call__` function.

### CODE REVIEW

**Comment by PeterH0323** [comment]
Hi @triple-Mu 
Thx for your contribution!
Pls add some doc for this feature, you can add some picture which is necessary then will be better. 😄

**Comment by triple-Mu** [comment]
> Hi @triple-Mu Thx for your contribution! Pls add some doc for this feature, you can add some picture which is necessary then will be better. smile

I'm not good at writing docs, if you could try this pr and write docs, I'd really appreciate it. 
If I have to write documentation, then I will close this pr, thanks again.

**Review by PeterH0323 — APPROVED** [review]
LGTM

**Review by hhaAndroid — APPROVED** [review]

**Comment by triple-Mu** [comment]
> LGTM

I have no idea about docs，could you help me about this.

**Pull request merged**
